username: tantalor
personal: http://johntantalo.com
projects:
  -
    name: emend
    desc: my first Google App Engine project
  -
    name: megaera
    desc: a Google App Engine web framework, factored out of <strong>emend</strong>
  -
    name: pretty_timedelta
    desc: an internationalized python utility for formatting positive and negative timedeltas, factored out of <strong>emend</strong>
  -
    name: graphjs
    desc: a Javascript class library for building and analyzing graphs
  -
    name: steel
    desc: a QUnit-compatible JavaScript testing framework, factored out of <strong>graphjs</strong>
  -
    name: raphael.planarity
    desc: a Rapha&euml;l implementation of Planarity with <strong>graphjs</strong>
  -
    name: raphael.graph
    desc: a Rapha&euml;l extension to create graphs using <strong>graphjs</strong>, factored out of <strong>raphael.planarity</strong>
  - name: numdayssince
    desc: A simple Google App Engine app to track the number of days since an event
  -
    name: tantalor.github.com
    desc: this document
